sonata_admin:
    title: 'ExpenseTracker'
    title_logo: custom/logo-short.png
    templates:
        layout:                     'standard_layout.html.twig'
        list:                       '@SonataAdmin/CRUD/list.html.twig'
        action:                     '@SonataAdmin/CRUD/action.html.twig'
        select:                     '@SonataAdmin/CRUD/list__select.html.twig'
        list_block:                 '@SonataAdmin/Block/block_admin_list.html.twig'
        short_object_description:   '@SonataAdmin/Helper/short-object-description.html.twig'
        batch:                      '@SonataAdmin/CRUD/list__batch.html.twig'
        inner_list_row:             '@SonataAdmin/CRUD/list_inner_row.html.twig'
        base_list_field:            '@SonataAdmin/CRUD/base_list_field.html.twig'
        pager_links:                '@SonataAdmin/Pager/links.html.twig'
        pager_results:              '@SonataAdmin/Pager/results.html.twig'
    dashboard:
        blocks:
            - { type: sonata.admin.block.admin_list, position: left }
    options:
        # Choices are: text, icon or all (default)
        list_action_button_content: icon

sonata_block:
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]
