# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.account:
        class: App\Admin\AccountAdmin
        calls:
        #     - [ setTemplate, ['edit', 'Account\account_edit.html.twig'] ]
        #     - [ setTemplate, ['show', 'Account\account_show.html.twig'] ]
        #     - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Account, controller: App\Controller\AccountAdminController, manager_type: orm, group: Banking, label: Accounts }

    admin.budget:
        class: App\Admin\BudgetAdmin
        calls:
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Budget, controller: App\Controller\BudgetAdminController, manager_type: orm, group: Budgets, label: Budget }

    admin.budget_item:
        class: App\Admin\BudgetItemAdmin
        calls:
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\BudgetItem, controller: App\Controller\BudgetItemAdminController, manager_type: orm, group: Budgets, label: Budget Item }

    admin.budget_sub_category:
        class: App\Admin\BudgetSubCategoryAdmin
        calls:
            # - [ setTemplate, ['list', 'Budget\budget_list.html.twig'] ]
            # - [ setTemplate, ['edit', 'CRUD\base_edit.html.twig'] ]
            # - [ setTemplate, ['show', 'CRUD\base_show.html.twig'] ]
            # - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\BudgetSubCategory, controller: App\Controller\BudgetSubCategoryAdminController, manager_type: orm, group: Categories, label: Budget Sub Categories }
            # - { name: sonata.admin, model_class: App\Entity\BudgetSubCategory, controller: App\Controller\BudgetSubCategoryAdminController, manager_type: orm, group: Admin, label: Budget Sub Categories, show_in_dashboard: false }

    admin.budget_main_category:
        class: App\Admin\BudgetMainCategoryAdmin
        calls:
            # - [ setTemplate, ['list', 'Budget\budget_list.html.twig'] ]
            # - [ setTemplate, ['list', 'Budget\budget_category_list.html.twig'] ]
            # - [ setTemplate, ['edit', 'CRUD\base_edit.html.twig'] ]
            # - [ setTemplate, ['show', 'CRUD\base_show.html.twig'] ]
            # - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\BudgetMainCategory, controller: App\Controller\BudgetMainCategoryAdminController, manager_type: orm, group: Categories, label: Budget Main Categories }
            # - { name: sonata.admin, model_class: App\Entity\BudgetMainCategory, controller: App\Controller\BudgetMainCategoryAdminController, manager_type: orm, group: Admin, label: Budget Categories }

    admin.comment:
        class: App\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Comment, controller: App\Controller\CommentAdminController, manager_type: orm, group: admin, label: Comment, show_in_dashboard: false }

    admin.department:
        class: App\Admin\DepartmentAdmin
        calls:
            # - [ setTemplate, ['list', 'Department\department_list.html.twig'] ]
            # - [ setTemplate, ['edit', 'CRUD\base_edit.html.twig'] ]
            # - [ setTemplate, ['show', 'CRUD\base_show.html.twig'] ]
            # - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Department, controller: App\Controller\DepartmentAdminController, manager_type: orm, group: Departments, label: Departments, on_top: true }

    admin.general_category:
        class: App\Admin\GeneralCategoryAdmin
        calls:
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\GeneralCategory, controller: App\Controller\GeneralCategoryAdminController, manager_type: orm, group: Categories, label: General Category }

    admin.purchase:
        class: App\Admin\PurchaseAdmin
        calls:
            # - [ setTemplate, ['edit', 'SonataCustomAdmin/PurchaseAdmin/edit.html.twig'] ]
#            - [ setTemplate, ['show', 'CRUD\base_show.html.twig'] ]
            # - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Purchase, controller: App\Controller\PurchaseAdminController, manager_type: orm, group: Purchases, label: Purchases, on_top: true }

    admin.purchase_line:
        class: App\Admin\PurchaseLineAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\PurchaseLine, controller: App\Controller\PurchaseLineAdminController, manager_type: orm, group: Purchase Lines, label: Purchase Line, show_in_dashboard: false }

    admin.supplier:
        class: App\Admin\SupplierAdmin
        calls:
            # - [ setTemplate, ['edit', 'CRUD\base_edit.html.twig'] ]
            # - [ setTemplate, ['show', 'Supplier\supplier_show.html.twig'] ]
            # - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Supplier, controller: App\Controller\SupplierAdminController, manager_type: orm, group: Suppliers, label: Suppliers, on_top: true }

    admin.unit:
        class: App\Admin\UnitAdmin
        calls:
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Unit, controller: App\Controller\UnitAdminController, manager_type: orm, group: Units, label: Units, on_top: true }

    admin.user_unit:
        class: App\Admin\UserUnitAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\UserUnit, controller: App\Controller\UserUnitAdminController, manager_type: orm, group: admin, label: UserUnit, show_in_dashboard: false }
