# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    admin.account:
        class: App\Admin\AccountAdmin
        calls:
        #     - [ setTemplate, ['edit', 'Account\account_edit.html.twig'] ]
        #     - [ setTemplate, ['show', 'Account\account_show.html.twig'] ]
        #     - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Account, controller: App\Controller\AccountAdminController, manager_type: orm, group: Banking, label: Accounts }

    # admin.add_funds:
    #     class: App\Admin\AddFundsAdmin
    #     calls:
    #         # - [ setTemplate, ['list', 'CRUD\base_list.html.twig'] ]
    #         - [ setTemplate, ['edit', 'Transaction\transaction_edit.html.twig'] ]
    #         - [ setTemplate, ['show', 'CRUD\base_show.html.twig'] ]
    #         - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
    #         - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
    #     tags:
    #         - { name: sonata.admin, model_class: App\Entity\Transaction, controller: App\Controller\AddFundsAdminController, manager_type: orm, group: admin, label: AddFunds, show_in_dashboard: false }

#     admin.bank_transfer:
#         class: App\Admin\BankTransferAdmin
#         calls:
#             - [ setTemplate, ['edit', 'Transaction\transaction_edit.html.twig'] ]
# #            - [ setTemplate, ['show', 'CRUD\base_show.html.twig'] ]
#             - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
#             - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
#         tags:
#             - { name: sonata.admin, model_class: App\Entity\Transaction, controller: App\Controller\BankTransferAdminController, manager_type: orm, group: admin, label: BankTransfer, show_in_dashboard: false }

    admin.budget:
        class: App\Admin\BudgetAdmin
        calls:
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Budget, controller: App\Controller\BudgetAdminController, manager_type: orm, group: Budgets, label: Budget }

    admin.budget_item:
        class: App\Admin\BudgetItemAdmin
        calls:
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\BudgetItem, controller: App\Controller\BudgetItemAdminController, manager_type: orm, group: Budgets, label: Budget Item }

    admin.budget_sub_category:
        class: App\Admin\BudgetSubCategoryAdmin
        calls:
            # - [ setTemplate, ['list', 'Budget\budget_list.html.twig'] ]
            # - [ setTemplate, ['edit', 'CRUD\base_edit.html.twig'] ]
            # - [ setTemplate, ['show', 'CRUD\base_show.html.twig'] ]
            # - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\BudgetSubCategory, controller: App\Controller\BudgetSubCategoryAdminController, manager_type: orm, group: Categories, label: Budget Sub Categories }
            # - { name: sonata.admin, model_class: App\Entity\BudgetSubCategory, controller: App\Controller\BudgetSubCategoryAdminController, manager_type: orm, group: Admin, label: Budget Sub Categories, show_in_dashboard: false }

    admin.budget_main_category:
        class: App\Admin\BudgetMainCategoryAdmin
        calls:
            # - [ setTemplate, ['list', 'Budget\budget_list.html.twig'] ]
            # - [ setTemplate, ['list', 'Budget\budget_category_list.html.twig'] ]
            # - [ setTemplate, ['edit', 'CRUD\base_edit.html.twig'] ]
            # - [ setTemplate, ['show', 'CRUD\base_show.html.twig'] ]
            # - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\BudgetMainCategory, controller: App\Controller\BudgetMainCategoryAdminController, manager_type: orm, group: Categories, label: Budget Main Categories }
            # - { name: sonata.admin, model_class: App\Entity\BudgetMainCategory, controller: App\Controller\BudgetMainCategoryAdminController, manager_type: orm, group: Admin, label: Budget Categories }

#     admin.cash_transfer:
#         class: App\Admin\CashTransferAdmin
#         calls:
#             # - [ setTemplate, ['list', 'CRUD\base_list.html.twig'] ]
#             - [ setTemplate, ['edit', 'Transaction\transaction_edit.html.twig'] ]
#             - [ setTemplate, ['show', 'CRUD\base_show.html.twig'] ]
#             - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
#             - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
#         tags:
#             - { name: sonata.admin, model_class: App\Entity\Transaction, controller: App\Controller\CashTransferAdminController, manager_type: orm, group: admin, label: Cash Transfer, show_in_dashboard: false }

#     admin.cash_withdrawal:
#         class: App\Admin\CashWithdrawalAdmin
#         calls:
#             - [ setTemplate, ['edit', 'Transaction\transaction_edit.html.twig'] ]
# #            - [ setTemplate, ['show', 'CRUD\base_show.html.twig'] ]
#             - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
#             - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
#         tags:
#             - { name: sonata.admin, model_class: App\Entity\Transaction, controller: App\Controller\CashWithdrawalAdminController, manager_type: orm, group: admin, label: Cash Withdrawal, show_in_dashboard: false }

    admin.comment:
        class: App\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\Comment, controller: App\Controller\CommentAdminController, manager_type: orm, group: admin, label: Comment, show_in_dashboard: false }

#     admin.currency_exchange:
#         class: App\Admin\CurrencyExchangeAdmin
#         calls:
#             - [ setTemplate, ['edit', 'Transaction\transaction_edit.html.twig'] ]
# #            - [ setTemplate, ['show', 'CRUD\base_show.html.twig'] ]
#             - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
#             - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
#         tags:
#             - { name: sonata.admin, model_class: App\Entity\Transaction, controller: App\Controller\CurrencyExchangeAdminController, manager_type: orm, group: admin, label: CurrencyExchange, show_in_dashboard: false }

    admin.department:
        class: App\Admin\DepartmentAdmin
        calls:
            # - [ setTemplate, ['list', 'Department\department_list.html.twig'] ]
            # - [ setTemplate, ['edit', 'CRUD\base_edit.html.twig'] ]
            # - [ setTemplate, ['show', 'CRUD\base_show.html.twig'] ]
            # - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Department, controller: App\Controller\DepartmentAdminController, manager_type: orm, group: Departments, label: Departments, on_top: true }

    admin.general_category:
        class: App\Admin\GeneralCategoryAdmin
        calls:
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\GeneralCategory, controller: App\Controller\GeneralCategoryAdminController, manager_type: orm, group: Categories, label: General Category }

    admin.invoice:
        class: App\Admin\InvoiceAdmin
        calls:
            - [ setTemplate, ['edit', 'Invoice\invoice_edit.html.twig'] ]
            # - [ setTemplate, ['edit', 'SonataCustomAdmin/InvoiceAdmin/edit.html.twig'] ]
            - [ setTemplate, ['show', 'Invoice\invoice_show.html.twig'] ]
            - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
            - [ setTemplate, ['button_edit', 'Button\check_edit_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Invoice, controller: App\Controller\InvoiceAdminController, manager_type: orm, group: Invoices, label: Invoices, on_top: false, default: true }

    admin.invoice_line:
        class: App\Admin\InvoiceLineAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\InvoiceLine, controller: App\Controller\InvoiceLineAdminController, manager_type: orm, group: Invoice Lines, label: Invoice Line, show_in_dashboard: false }

    admin.invoice_part_payment:
        class: App\Admin\InvoicePartPaymentAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\InvoicePartPayment, controller: App\Controller\InvoicePartPaymentAdminController, manager_type: orm, group: admin, label: InvoicePartPayment, show_in_dashboard: false }

#     admin.money_return:
#         class: App\Admin\MoneyReturnAdmin
#         calls:
#             - [ setTemplate, ['edit', 'Transaction\transaction_edit.html.twig'] ]
# #            - [ setTemplate, ['show', 'CRUD\base_show.html.twig'] ]
#             - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
#             - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
#         tags:
#             - { name: sonata.admin, model_class: App\Entity\Transaction, controller: App\Controller\MoneyReturnAdminController, manager_type: orm, group: admin, label: MoneyReturn, show_in_dashboard: false }


    admin.purchase:
        class: App\Admin\PurchaseAdmin
        calls:
            # - [ setTemplate, ['edit', 'SonataCustomAdmin/PurchaseAdmin/edit.html.twig'] ]
#            - [ setTemplate, ['show', 'CRUD\base_show.html.twig'] ]
            # - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Purchase, controller: App\Controller\PurchaseAdminController, manager_type: orm, group: Purchases, label: Purchases, on_top: true }

    admin.purchase_line:
        class: App\Admin\PurchaseLineAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\PurchaseLine, controller: App\Controller\PurchaseLineAdminController, manager_type: orm, group: Purchase Lines, label: Purchase Line, show_in_dashboard: false }

    admin.supplier:
        class: App\Admin\SupplierAdmin
        calls:
            # - [ setTemplate, ['edit', 'CRUD\base_edit.html.twig'] ]
            # - [ setTemplate, ['show', 'Supplier\supplier_show.html.twig'] ]
            # - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Supplier, controller: App\Controller\SupplierAdminController, manager_type: orm, group: Suppliers, label: Suppliers, on_top: true }

    admin.transaction:
        class: App\Admin\TransactionAdmin
        calls:
            - [ setTemplate, ['edit', 'Transaction\transaction_edit.html.twig'] ]
            - [ setTemplate, ['show', 'Transaction\transaction_show.html.twig'] ]
            - [ setTemplate, ['delete', 'CRUD\delete.html.twig'] ]
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
            - [ setTemplate, ['button_edit', 'Button\check_edit_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Transaction, controller: App\Controller\TransactionAdminController, manager_type: orm, group: Banking, label: Transactions, default: true }

    admin.unit:
        class: App\Admin\UnitAdmin
        calls:
            - [ setTemplate, ['button_create', 'Button\create_button.html.twig'] ]
        tags:
            - { name: sonata.admin, model_class: App\Entity\Unit, controller: App\Controller\UnitAdminController, manager_type: orm, group: Units, label: Units, on_top: true }

    admin.user_unit:
        class: App\Admin\UserUnitAdmin
        tags:
            - { name: sonata.admin, model_class: App\Entity\UserUnit, controller: App\Controller\UserUnitAdminController, manager_type: orm, group: admin, label: UserUnit, show_in_dashboard: false }
